import { useState } from "react";
import './Posts_styles.scss';

const PostForm = ({onSubmit}) => {
  // using 1 as default values for id and likes where the exact values are generated by mocker itself, but if we provide null or 0 it is showing The error “Cannot read properties of null (reading ‘toJSON’)”
  const [formData, setFormData] = useState({
    userId: "",
    title: "",
    content: "",
    id: 1,
    likes : 1
  });
  

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: name === 'userId' ? Number(value) : value // Convert userId to number
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    onSubmit(formData);
  };

  const handleReset = () => {
    setFormData({
      userId: "",
      title: "",
      content: "",
    });
  };

  return (
    <div className="min-w-80 max-w-lg mx-auto mt-10 p-6 bg-gradient-to-tr from-purple-400 via-purple-600 to-purple-700 rounded-lg shadow-xl">
      <h2 className="text-2xl font-bold mb-6">Create a Post</h2>
      <form onSubmit={handleSubmit}>
        <div className="mb-4">
          <label
            htmlFor="userId"
            className="post-form-labels"
          >
            User ID
          </label>
          <input
            type="number"
            id="userId"
            name="userId"
            onChange={handleChange}
            className="post-form-inputs"
          />
        </div>
        <div className="mb-4">
          <label
            htmlFor="title"
            className="post-form-labels"
          >
            Post Title
          </label>
          <input
            type="text"
            id="title"
            name="title"
            onChange={handleChange}
            className="post-form-inputs"
          />
        </div>
        <div className="mb-4">
          <label
            htmlFor="content"
            className="post-form-labels"
          >
            Post Content
          </label>
          <textarea
            id="content"
            name="content"
            onChange={handleChange}
            className="post-form-inputs"
          />
        </div>
        <div className="flex justify-between">
          <button
            type="button"
            onClick={handleReset}
            className="post-form-buttons bg-gray-500 hover:bg-gray-600"
          >
            Reset
          </button>
          <button
            type="submit"
            className="post-form-buttons bg-green-500 hover:bg-green-600"
          >
            Submit Post
          </button>
        </div>
      </form>
    </div>
  );
};

export default PostForm;
